require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'spec/dummy/db/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Layout/LineLength:
  Max: 120

# No space makes the method definition shorter and differentiates
# from a regular assignment.
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Max: 6

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - and
    - if
    - in
    - for

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
